name: Your Fork

on:
  pull_request_target:
    types: [opened]

jobs:
  close:
    if: github.repository == 'chilukuriphani/intuitive-terraform-lab'
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Optional. Post a issue comment just before closing a pull request.
        comment: "Intuitive Lab"
